# Top 5 most useful labels for PR organization

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: ['*.md', 'docs/**/*']

# Generator and template changes (core functionality)
generator:
  - changed-files:
    - any-glob-to-any-file: ['generators/**/*']

# Testing changes
tests:
  - changed-files:
    - any-glob-to-any-file: ['test/**/*', '**/*.test.js', '**/*test*']

# CI/CD and workflow changes
ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package*.json', 'requirements*.txt', '**/requirements*.txt']
